### ISSUE TITLE
Models are ignored

### ISSUE THREAD

**Issue by jaumard** [saviogl/generator-sails-plugin-hook#2]
Models are not load when sails lift (version 0.11.0). Just basic test : 

yo sails-plugin-hook
Copy/paste under a new sails project 
Create a model file
Launch sails 
Check database for table creation 
Sails model are create fine but not hook model

**Comment by saviogl** [comment]
You gotta install your newly created hook into your sails project as npm module.

Inside your sails app run ’npm install <your-hook-name>’ or you can make use of  ’npm link’ to install local modules to your project.

 

Keep me posted on this issue

Regads,

Sávio Lucena

**Comment by jaumard** [comment]
Yes I copy it under node_modules folder of course but it's not working, all files are loaded correctly but not model files. I can send you the all test project if you want

**Comment by jaumard** [comment]
My bad sorry !  The copy/paste failed on some files :/ everything is working :)
Thanks for your help !

**Comment by saviogl** [comment]
That’s awesome Jaumard, really glad that everything worked out ok!

Sávio Lucena
